Port si7210 driver with new driver framework
ethz-asl/ethzasl_fw_px4 pull request #18
Opened 2021-04-29 20:59 UTC by Jaeyoung-Lim

**Describe problem solved by this pull request**

**Describe your solution**
This commit ports the si7210 hall sensor to the new driver framework.
This is implemented on top of https://github.com/ethz-asl/ethzasl_fw_px4/pull/17

**Test data / coverage**
- WIP

**Additional context**
- This PR is against https://github.com/ethz-asl/ethzasl_fw_px4/pull/17

2021-05-25 10:41 UTC, ASM3 requested changes
General remark: functionality, boot sequence and timing could not be verified as the HW is not available

2021-06-01 13:00 UTC, acfloria commented on src/drivers/si7210/si7210.cpp
>  }
I checked it with some print statements. This probe is called but not the base Vane::probe one.
I also found that probably (due to this) the starting without keep retrying is not very reliable.

2021-06-21 06:53 UTC, Jaeyoung-Lim commented on src/drivers/si7210/CMakeLists.txt
> +		# -DDEBUG_BUILD
Done!

2021-06-21 06:54 UTC, Jaeyoung-Lim commented on src/drivers/si7210/si7210.cpp
> +	// bool si7210_notify = true;
Removed comment

2021-06-21 11:51 UTC, Jaeyoung-Lim commented on src/drivers/si7210/si7210.h
> +	State _state{State::RequireConfig};
Actually not, I have removed the crc now, thanks!

2021-06-23 13:11 UTC, ASM3 commented on src/drivers/si7210/si7210.cpp
>  }
great

2021-06-24 08:06 UTC, ASM3 commented
lgtm

2021-06-24 11:25 UTC, Jaeyoung-Lim commented
@ASM3 Thanks! Merging!

2021-06-24 11:25 UTC, merged